
services:
  web:
    build: .
    command: >
      bash -c "python manage.py makemigrations && 
               python manage.py migrate &&
               gunicorn --bind 0.0.0.0:8000 core.wsgi:application"
    volumes:
      - .:/app
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/app/staticfiles/
      - ./media:/app/media/
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
