# Generated by Django 5.1.6 on 2025-02-13 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_course_subject'),
        ('user', '0002_userprofile_is_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.trainingsubject'),
        ),
    ]
