# Generated by Django 5.1.6 on 2025-02-13 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_course_subject'),
        ('user', '0003_userprofile_is_affiliated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='trainer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_course', to='user.userprofile'),
        ),
    ]
