# Generated by Django 5.1.6 on 2025-02-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
    ]
